version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/html
    ports:
      - ${APP_PORT}:8000
    environment:
      - TZ: 'Asia/Tokyo'

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
    environment:
      - TZ: 'Asia/Tokyo'